"""allow null times in operating hours

Revision ID: 2449b92ebf6d
Revises: 2e842156351d
Create Date: 2026-02-25 14:14:17.232209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2449b92ebf6d'
down_revision: Union[str, Sequence[str], None] = '2e842156351d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merge_groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('operating_hours', 'open_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('operating_hours', 'close_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('operating_hours', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('special_hours', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('special_hours_date_key'), 'special_hours', type_='unique')
    op.alter_column('tables', 'is_mergeable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('tables', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('tables', 'is_mergeable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_unique_constraint(op.f('special_hours_date_key'), 'special_hours', ['date'], postgresql_nulls_not_distinct=False)
    op.alter_column('special_hours', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('operating_hours', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('operating_hours', 'close_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('operating_hours', 'open_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('merge_groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
