"""replace merge groups with reservation tables join

Revision ID: b873c42ebe4b
Revises: 2449b92ebf6d
Create Date: 2026-02-25 15:52:09.130456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b873c42ebe4b'
down_revision: Union[str, Sequence[str], None] = '2449b92ebf6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create the new join table
    op.create_table('reservation_tables',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id', 'table_id')
    )
    # 2. Drop FK constraints that reference merge_groups BEFORE dropping the table
    op.drop_constraint(op.f('tables_merge_group_id_fkey'), 'tables', type_='foreignkey')
    op.drop_constraint(op.f('reservations_merge_group_id_fkey'), 'reservations', type_='foreignkey')
    op.drop_constraint(op.f('reservations_table_id_fkey'), 'reservations', type_='foreignkey')
    # 3. Now safe to drop merge_groups
    op.drop_index(op.f('ix_merge_groups_id'), table_name='merge_groups')
    op.drop_table('merge_groups')
    # 4. Clean up old columns
    op.drop_column('reservations', 'merge_group_id')
    op.drop_column('reservations', 'table_id')
    op.drop_column('tables', 'is_mergeable')
    op.drop_column('tables', 'merge_group_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('merge_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('is_mergeable', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tables_merge_group_id_fkey'), 'tables', 'merge_groups', ['merge_group_id'], ['id'])
    op.add_column('reservations', sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reservations', sa.Column('merge_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('reservations_merge_group_id_fkey'), 'reservations', 'merge_groups', ['merge_group_id'], ['id'])
    op.create_foreign_key(op.f('reservations_table_id_fkey'), 'reservations', 'tables', ['table_id'], ['id'])
    op.create_table('merge_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('merge_groups_pkey'))
    )
    op.create_index(op.f('ix_merge_groups_id'), 'merge_groups', ['id'], unique=False)
    op.drop_table('reservation_tables')
    # ### end Alembic commands ###
